name: Run Browserify
on: [push]
jobs:
  Run-Browserify:
    runs-on: ubuntu-latest
    steps:
      - run: "npm install -g browserify"
      - run: "browserify client/client.js  shared/constants.js -o public/js/bundle.js"
