name: Run Browserify
on: [push]
jobs:
  Run-Browserify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install
        run: npm install
      - name: Install Browserify
        run: npm install -g browserify
      - name: Run Browserify
        run: npm ci

      - name: check for changes
        run: git status
      - name: stage changed file
        run: git add public/js/bundle.js
      - name: commit code
        run: git commit -m "auto update bundle.js"
      - name: push code
        run: git push
