name: Run Browserify
on: [push]
jobs:
  Run-Browserify:
    runs-on: ubuntu-latest
    steps:
      - run: "npm install browserify && browserify shared/constants.js public/js/client.js -o public/js/bundle.js"
